### ISSUE TITLE
Structured Data Critical Issues From Google

### ISSUE THREAD

**Issue by lordzden** [Automattic/WP-Job-Manager#1130]
Current Site Setup:
I have the latest WP version
I have the latest WP Job Manager
I have the latest theme update

**Issue:
Structured Data JobPosting mark up has a lot of critical errors from Google Webmasters** 

Example, errors from Google: 
“Missing or invalid field: hiringOrganization.name (Critical issue)”
“Missing or invalid field: jobLocation (Critical issue)”
“Missing or invalid field: datePosted (Critical issue)”
“Missing or invalid field: jobLocation.address (Critical issue)”. 

Please see screenshot from Google Console:
https://www.screencast.com/t/ZWSeshkoFY5w 

Please see this link for solution:
https://developers.google.com/search/docs/data-types/job-postings#definitions

thanks.

**Comment by jom** [comment]
Duplicate of #1046; Closed and will feature will be added in upcoming 1.28.0 (slated for release next week).

**Comment by lordzden** [comment]
Thanks for the latest update. I still have the issues. Please see screenshot. 
![missing required markups](https://user-images.githubusercontent.com/4757319/29154476-74ab39c8-7dc7-11e7-809f-2641b8b2de3d.png)

**Comment by jom** [comment]
@lordzden Hi there! I'm not able to replicate on a job that has the job title and location fields entered. What is the URL of the job posting?

**Comment by praitosola** [comment]
Hi, I am getting this same issue today (we updated the plugin yesterday - is this something to do with that? - we use Listable theme - so we do not have any Hiring Organizations or Base Salaries, etc... ): 

Search Console has identified that your site is affected by 11 new Job Postings related issues. This means that Job Postings may be negatively affected in Google Search results. We encourage you to fix these issues.

Top 5 new issues found, ordered by number of affected pages:
Missing or invalid field: employmentType
Missing or invalid field: hiringOrganization.name
Missing or invalid field: baseSalary
Missing or invalid field: validThrough
Missing or invalid field: jobLocation.address.addressRegion

**Comment by seanjarboe** [comment]
Same issues as above poster since November 2017. and the issues are building.

Current Site Setup:
I have the latest WP version
I have the latest WP Job Manager
I have the latest theme update

Issue:
Structured Data JobPosting mark up has a lot of critical errors from Google Webmasters
Missing or invalid field: jobLocation.address.addressRegion 


![image](https://user-images.githubusercontent.com/36413351/36103315-05a5a0e2-0fdd-11e8-9597-698dda8022a5.png)

![image](https://user-images.githubusercontent.com/36413351/36103378-30759160-0fdd-11e8-8bff-83406e45805e.png)

**Comment by jom** [comment]
@seanjarboe For `employmentType` Make sure you are requiring job types and go through all your job types are assigned an employment type. For the `addressRegion` issue, make sure you have your Google Maps key set in settings. Fixing this won't fix old job listings, though. Visit the forums if you continue running into issues.

**Comment by soaresefixe** [comment]
I still have the same problem. In what forums can I go to see some answers to the above problem?

Cheers, Ivo
