### ISSUE TITLE
Job list breaks in newest update, when used with Polylang

### ISSUE THREAD

**Issue by larsschellhas** [Automattic/WP-Job-Manager#1590]
Sorry, had to be quick. Title says everything.

**Comment by jom** [comment]
Especially with third-party conflicts, please outline steps to reproduce from fresh install.

**Comment by larsschellhas** [comment]
Okay, sorry, I had really no time yesterday. 
With the newest version of Polylang and WP Job Manager we´ve got the problem on the page where we used the [jobs] shortcode. The page is available only in one language, but it makes no difference which language is activated right now. 
It looks then like this and won´t find any job offers:
![image](https://user-images.githubusercontent.com/14281234/45514518-39feea00-b7ae-11e8-9b47-e70dc1721481.png)

But when I roll back to 1.31.2 it works normally and looks like this:
![image](https://user-images.githubusercontent.com/14281234/45514690-bc87a980-b7ae-11e8-8eed-b811edc3d920.png)

**Comment by jom** [comment]
Thanks for the update. This is probably from #1573 

For now, try this to remove that added functionality:
```
remove_filter( 'pll_is_ajax_on_front', 'polylang_wpjm_doing_ajax' );
```

**Comment by larsschellhas** [comment]
I activated both and looked into the logs, but there is nothing about one of the plugins :/
It has some notices about a deprecated php function used in my theme, but I guess, it´s not about the theme since it did work previously

**Comment by larsschellhas** [comment]
I just looked for the added functionality, but it is not even published yet and therefore not existing in my installation. #1573 was merged just 18 days ago.
But the problems occur since the release of 1.31.3 one month ago - in 1.31.2 it was fine.

**Comment by larsschellhas** [comment]
Will this be fixed in the near future? Otherwise I´ll have to switch to another plugin...

**Comment by jom** [comment]
Might be worth manually updating that file from `master` and see if that change fixes it? I don't have a Polylang instance to test with right now.

**Comment by jom** [comment]
I'm not able to reproduce this with a fresh install of Polylang and WPJM. Are you still experiencing this problem? Closing for now, but reply if you're still having issues.

**Comment by Jokiller230** [comment]
Hello there!
I recently did a rather large jump from 1.40.2 all the way up to 2.3.0, and the same issue is happening on my end.
At the same time, I also went from Polylang 3.4.3 to 3.6.1.

So far, I have tried downgrading just Polylang, which didn't resolve the issue.
Disabling Polylang did resolve it, though.

Downgrading WP Job Manager back to 1.40.2 also resolved it.

There don't seem to be any other clues as to what's happening here.
