### ISSUE TITLE
Edit listing invalid image path error for image replaced by CDN URL

### ISSUE THREAD

**Issue by rickbeeloo** [Automattic/WP-Job-Manager#2035]
**Describe the bug**
_I'm not sure if this should be called a bug or enhancement so please change if necessary._
We use the[ Listify theme](https://themeforest.net/item/listify-wordpress-directory-theme/9602611) on our website, and recently installed an image optimization plugin ([Optimole](https://optimole.com/)) to process the images. This plugin adds their CDN url as a prefix to the original in order to refer to the processed image. While all working fine we now noticed that this causes an "invalid path error" when a user wants to edit their listing. This since in the `/includes/forms/class-wp-job-manager-form-submit-job.php` the code checks whether the image path start with <domain>/wp-content/uploads whereas in our case the URL looks like:  `https://mlpnsv5uiutt.i.optimole.com/........../https://salonstoelhuren.flywheelstaging.com/wp-content/uploads/job-manager-uploads/featured_image/2020/07/test.jpeg`. 

**To Reproduce**
Install Optimole and edit a listing. 

**Expected behavior**
Also allow images to be served from an external CDN when the images is the same (not sure if this would cause a security risk?)

In my case I now could add a code like this (P.s. I'm not a PhP programmer so code probably sucks)
```
if (strpos( $file_url, 'optimole') !== false ) {
   $file_url = substr($file_url, strpos($file_url, 'https://', strpos($file_url, 'https://')+1), strlen($file_url)); 
}
```
but it would be tedious to change this every time after an update, so if someone with more PHP skills now how I could add this to functions.php or something that would be great!

**Isolating the problem (mark completed items with an [x]):**
- I have deactivated the Optimole plugin and that solved the issue

**WordPress Environment**
- WordPress Version: 5.4.2
- WP Job Manager Version: 1.34.2
- PHP Version: 7.3

**Comment by tripflex** [comment]
I can confirm this is a bug when it comes to using a CDN (or offloading images/files) 

Specifically the problem is with the `validate_fields()` method which checks against the URL of the file, specifically and only allowing it to be the value of `baseurl` from `wp_upload_dir()` function.

https://github.com/Automattic/WP-Job-Manager/blob/30db4c0dbf46b74b00ea977e3395635a3dfb6fb2/includes/forms/class-wp-job-manager-form-submit-job.php#L374-L386

This is also an issue with anybody using WP Engine, as their CDN will serve files from a completely different domain:
https://wpengine.com/support/how-does-a-cdn-work/

I think the best solution would be to add a filter of allowed URLs when doing the check, or add a filter to disable that check entirely (as right now there's basically nothing anybody can do about this).

**Comment by tripflex** [comment]
Which was introduced by this commit d7954bb449571d99f2d5a22c43713e51de4aa8d6 .. https://github.com/Automattic/WP-Job-Manager/pull/1989

.. so the only option right now is to downgrade WP Job Manager to 1.34.1 @renatho

**Comment by gkaragia** [comment]
Hello @dave3322, this issue should be fixed in the latest version (1.34.3) of WP Job Manager. Do you use the latest one? If not can you please upgrade and test again?

**Comment by dave3322** [comment]
I do use the latest version 1.34.3. That said i will delete all files from the server and download a freshcopy and retest and let you asap.

Many Thanks

**Comment by dave3322** [comment]
I have deleted and reinstalled wp job manager the same issue.
You careate a new listing and add an image.
The image successfully shows on the back end and it points to amazon s3 folder
You go back to the listing and just press save again and go abck to the listing the picture disappears on the front end.

WordPress Environment

WordPress Version: 5.5.1
WP Job Manager Version: 1.34.3

**Comment by rickbeeloo** [comment]
@dave3322 You still get the invalid path message? In my case, it was caused by an image optimization plugin that changed the paths of the images to their optimized variants. I excluded this URL replacement for the upload/edit pages. Perhaps you can try to disable image related plugins, like the one you mentioned, and see if that resolves it? If so contact the plugin developers to see how you can exclude specific pages

**Comment by dave3322** [comment]
@rickbeeloo 

I don't get the invalid image path error. 

I have seen that the filter is set to false, hence it allows the external image when you submit. 

the issue is when you want to edit the submission. If you click 'save' all seems fine, when you go to the front end and refresh the featured image disappears. I have tried with with two different CDN plugins

@tripflex  explained the same issue on jul 9.

I think this issue is slightly different from wpjm rejecting external images on submission. This is wpjm rejecting external images on edit without displaying an error. (Unless I don't know where to look for the error)

To replicate,
1. Download any CDN external image plug that changes the URL of your images so they are sourced from the CDN URL.

2. Create a listing with a featured image and submit

3. Go to front end and check. Featured image is there and if you inspect the URL of the image, it points to the CDN URL.

4. Now go back and click edit the listing, and just save, you don't necessarily have to make any changes, but click save again.

5. Now go back to the listing. Featured image disappears.

This is the issue.
