### ISSUE TITLE
chrome and chromium-based browser behaviour on ajax-loading

### ISSUE THREAD

**Issue by gluehbirne123** [Automattic/WP-Job-Manager#2070]
**Describe the bug**
On the site "jobs" is a "load more" button. if i click it on chrome and chromium-based browsers (e.g. MS edge) the buttons load more job-items, but the content is loaded above the button and the user has to sroll up to see the new loaded items.

UPDATE - this is reproducible on Android, as well as Chrome for Desktop when using the responsive view.

**To Reproduce**
1. Open site in chrome or chrome-base browser
2. Go to sub-site "jobs"
3. click on the load_mor_jobs_button

**Expected behavior**
the new loaded items are loaded under the current viewport and the user can scroll down till the maximum amount of items are reached to the next "load more"-button

**Comment by cena** [comment]
Reported in https://wordpress.org/support/topic/behaviour-after-click-load-more-button/

**Comment by bindlegirl** [comment]
Reported here as well: https://wordpress.org/support/topic/weird-scroll-behaviour-on-android-for-jobs-shortcode/

**Comment by alexsanford** [comment]
I just tested on the latest Chrome and Brave browsers (on OSX), and I'm not seeing the issue

**Comment by gluehbire** [comment]
Hi @alexsanford @bindlegirl , it is fixed in the middle of november with an update. i didn´t check the issue here, sorry. i cannot find the option to mark it as solved....

**Comment by bindlegirl** [comment]
Sorry, I failed to clarify the issue that was reported was referring to Android and Chrome on desktop but using the responsive view. I was able to reproduce both scenarios. The behavior is the same as described in the first issue. Should I create a new issue for Android?

**Comment by alexsanford** [comment]
Added a note to the description above 👍

**Comment by ferdman** [comment]
also reported here: https://wordpress.org/support/topic/load-more-listings-mobile-behaviour

I'm having this issue on Android devices. I haven't seen the problem yet on iOS devices. I am using the Astra theme and switching to TwentyTwenty actually resolved it. Since other people are reporting it too I don't believe it's strictly an "Astra" issue. I'll try to test it with different themes as well soon and let you know with an update.

**Comment by ateufel** [comment]
i reported this one: https://wordpress.org/support/topic/weird-scroll-behaviour-on-android-for-jobs-shortcode/
it is definitely not solved even with the latest versions, but only happening on android (with firefox and chrome) and it does not work either with chrome on desktop in the mobile view (on ubuntu, btw). careful, again, it DOES work in the desktop view, it only affects the mobile view.

**Comment by mikeyarce** [comment]
I tried reproducing this today with no luck.  I tried using Chrome with a Mobile view but it would not scroll down like described.  I also tried with the Astra theme as that one was mentioned a few times here but it also didn't have any issues.

I'm going to close this for now as we can't reproduce with the instructions.  If this is still happening to anyone, please post detailed instructions on how to reproduce with the exact setup so we can take a better look 😄
