### ISSUE TITLE
Conflict with Jetpack's Photon: Featured Image removed when editing listing from frontend

### ISSUE THREAD

**Issue by jeherve** [Automattic/WP-Job-Manager#576]
Steps to reproduce:

0. Install Jetpack, activate [Photon](http://jetpack.me/support/photon), install WPJM.
1. Create a few listings from wp-admin, including both a Featured Image and some gallery images.
2. Create a `listings` child page, and add `[job_dashboard]` to that page.
3. Access that page, and click on edit to modify one of the listings from the frontend. The listing description as well as the featured image and the gallery images are all displayed there.
4. Add a few words to the description, and save your changes.
5. The Featured Image still appears as the "cover image" on the listing's page.
6. Open the listing in wp-admin.
    - The Featured Image is gone.

This only happens when the Photon module is active.

Could it be because the image displayed on the frontend is different from the actual featured image (it is served from a WordPress.com subdomain, `i{0-2}.wp.com`), so when the form is submitted when saving your changes in the frontend editor, the media URL doesn't match a possible attachment on the site?

Reported in 2435021-t

**Comment by aheckler** [comment]
I haven't tried to repro this or anything, but would be curious to hear @mikejolley's thoughts. 

My initial reaction is to `wontfix`, because job listings should never be submitted via wp-admin. When our users say that they've done so and it messes up something with the job, we emphasize that everything should be done via the front-end.

With front-end submission, WPJM does not set featured images on job listings, nor can you add images to the job description:

![screen shot 2016-01-27 at 9 24 05 am](https://cloud.githubusercontent.com/assets/5512652/12616195/d12d8ab6-c4d7-11e5-898c-1735055ff3b5.png)

So yeah, seems pretty edge-casey to me. Open to hearing other opinions though! :smile:

**Comment by jeherve** [comment]
To be clear, the problem happens when editing listing on the frontend. Step 7 above is just an easy way to spot the error by looking at the Featured Image field in wp-admin.

**Comment by aheckler** [comment]
Not sure what you mean... In Step 2, you said:

> Create a few listings from wp-admin, including both a Featured Image and some gallery images.

... all three of which should never happen if people are using the plugin correctly.

**Comment by jeherve** [comment]
oh.hm. My bad. It's been a while since I created that ticket. Nevermind my last comment.

**Comment by spencerfinnell** [comment]
I'm not sure submitting a job via the backend should be considered an edge case. The first feature on the site:

> Add, manage and categorise job listings using the familiar WordPress UI.

**Comment by mikejolley** [comment]
WPJM doesn't use featured images itself, but does set them for some theme's benefit. It also tries to match an image URL to an attachment ID which is likely where this is falling down due to the replacement by Photon.

ideally we'd store non-CDN URLs, but it may not be possible to prevent the CDN changing URLs.

**Comment by spencerfinnell** [comment]
@mikejolley This issue would still exist on normal file upload fields added to the submission form though wouldn't it?

**Comment by mikejolley** [comment]
@spencerfinnell most likely but not a lot you can do if the CDN plugin changes the URL returned by WP uploader..

**Comment by Rappadappa77** [comment]
Hey Guys,

I haven't been following your post since last year, but I'm the individual who told @jeherve to look into the issue, hence why he created the post, JetPack has been updated for the last couple of months including today and I still have the same issue, I'm wondering if I'm the only person in the World who has this problem. So thank you to @mikejolley @spencerfinnell @aheckler for looking into this for me and trying to solve the problem.

Howard

**Comment by jeherve** [comment]
@Rappadappa77 Are you running the latest version of the WP Job Manager plugin, and still experiencing issues?

**Comment by Rappadappa77** [comment]
@jeherve Yes I'm running WP Job Manager 1.25.0 which was updated 3 months ago and yes the problem is still there.

Howard

**Comment by jeherve** [comment]
Thanks. I reopened the issue, so we can take another look.

**Comment by Rappadappa77** [comment]
Thank you man, much appreciated.

**Comment by spencerfinnell** [comment]
Have had multiple reports of disabling Photon fixing the issue. Definitely still an issue on non-featured image fields.

**Comment by Rappadappa77** [comment]
@spencerfinnell Yes that fix the issue, but don't think it would be a good idea, hopefully can find this pesky bug.

**Comment by Rappadappa77** [comment]
Hey Guys,

Hope you all are doing fine?
Still no solution for this issue, Astoundify did an update where they said they disabled Photon, i don't see it in the JetPack admin, but the issue still persist, so not sure what happened there :(

Howard

**Comment by spencerfinnell** [comment]
@Rappadappa77 Temporarily disable Listify, then disable the Photon module in Jetpack, then enable Listify again. 

Listify only hides the module from appearing in the list so the current setting remains active.

**Comment by Rappadappa77** [comment]
@spencerfinnell Thank you for the information, that worked perfectly 👍 

Howard

**Comment by Rappadappa77** [comment]
I hope you guys really find a solution for this because i can really see the slowdown in my website 👎.

Howard

**Comment by AleksIralda** [comment]
Hey, you're not alone. I have same problem, I hope a solution for this.

**Comment by jom** [comment]
Just a note: I think this has been fixed for the Featured Images/Company Logo. 

@spencerfinnell Is this for folks who have added a custom `file` fields? (Via the `Field Editor` plugin or `submit_job_form_fields` filter?)

**Comment by spencerfinnell** [comment]
Correct. It fails on the `file` upload field because the value is stored as a URL instead of an ID. The initial versions of WP Job Manager did not create actual attachments for uploaded files so this was more difficult to solve. However now I think some sort of backwards compatible storage method to convert values to IDs may be possible.

**Comment by bikedorkjon** [comment]
User reported issue in 3239255-t @jom what is left to do here to get this fixed?

**Comment by linusfeldt** [comment]
I believe this is still an issue. I am using WPJM together with Listify theme and Jetpack Photon. Image was originally uploaded with the front-end uploader, whenever someone edits the listing in the front-end (no matter what edit), file in screenshot is created.

<img width="356" alt="screen shot 2017-06-13 at 16 41 15" src="https://user-images.githubusercontent.com/6987666/27088132-2b67a320-5057-11e7-8146-ba44c501560a.png">

**Comment by aheckler** [comment]
@linusfeldt That looks like this issue here: https://github.com/Automattic/WP-Job-Manager/issues/603

**Comment by linusfeldt** [comment]
@aheckler Fair enough I am not that technical. I believe the issue is quite similar to the one described above after all.

- When right clicking on the image (screen below) in the front-end editor I get this URL: "https://i0.wp.com/example.com/wp-content/uploads/job-manager-uploads/featured_image/2017/06/ggmoments.jpg?zoom=2&fit=25601707&ssl=1", while the original upload is located here: "https://example.com/wp-content/uploads/job-manager-uploads/featured_image/2017/06/ggmoments.jpg"

This is probably why the mismatch occur and a new file is created. 

<img width="546" alt="screen shot 2017-06-13 at 17 08 45" src="https://user-images.githubusercontent.com/6987666/27089560-03d7fe8c-505b-11e7-9238-e82c73ddcb4a.png">

**Comment by spencerfinnell** [comment]
Might be as simple as just telling Photon to not do anything on the submit/edit pages: https://jetpack.com/2013/05/03/skip-a-image-with-photon/

**Comment by linusfeldt** [comment]
@spencerfinnell sounds like a plan. I can test it right away. Just need find a way to identify the ID of that specific page(s).

**Comment by spencerfinnell** [comment]
You can use `if ( is_page( get_option( 'job_manager_submit_job_form_page_id' ) ) ) {}`

**Comment by linusfeldt** [comment]
@spencerfinnell Something like this? I am afraid it got too technical for me...

function no_photon_by_page() {
  if ( is_page( get_option( 'job_manager_submit_job_form_page_id' ) ) ) {}
    add_filter( 'jetpack_photon_skip_image', '__return_true');
  }
}
 
add_action('wp', 'no_photon_by_page');

**Comment by spencerfinnell** [comment]
Add this to your functions.php to test: https://gist.github.com/spencerfinnell/4ff80fe364402281560a1f98e028c7b1

**Comment by linusfeldt** [comment]
@spencerfinnell Thanks!

Although it is still not working. As soon as I upload an image, click save. And when I open the edit page again the image is served from Photon. When I click save a trash file is created in the media library.

**Comment by spencerfinnell** [comment]
Make sure your submission page is set in Job Listings > Settings > Pages. Will test on my end too.

**Comment by linusfeldt** [comment]
No luck. I even tried to insert the ID of the page where I have the [submit_job_form] shortcode, with the same result.

**Comment by linusfeldt** [comment]
Alright, I got some more clues:

I got the "Company Logo" to load without Photon using a variation of the code above. However the "Cover Image" / Featured Image is still loaded from Photon. I believe it's due to the fact that Featured Images - specifically the downsizing of Featured Images- are handled different, and is producing this issue. 

("Photon currently only acts on images in posts and pages, as well as featured images/post thumbnails via the image_downsize filter.")

I found a post talking about it here: https://ethitter.com/2013/07/disable-jetpacks-photon-module-in-specific-situations/

The code does not work inside my functions.php and this is where I get stuck.

**Comment by linusfeldt** [comment]
@spencerfinnell Did you manage to take a look at this?

**Comment by annezazu** [comment]
@spencerfinnell  noting that a user tried [what you suggested](https://github.com/Automattic/WP-Job-Manager/issues/576#issuecomment-308209693) in 669730-zen and the fix did not work.

**Comment by linusfeldt** [comment]
"Until now, when filtering content, our image content delivery network (CDN), Photon, removed width and height attributes from image tags. This was done to make sure images were never distorted, regardless of how they were being inserted into a post or page.

We’ve now improved this process and will avoid removing those attributes when we can. Photon will preserve these attributes in tags present in slideshows, galleries, custom (non-Jetpack) galleries, and individual images."

Could this possibly be related? (From the latest patch notes)

**Comment by dave3322** [comment]
Gents I have read the above, I dont beleive this is a jetpack issue. This is any issue with any cdn plugin
So far this issue is consistent with 
1. Jetpack - Photon
2. 'WP Offload Media Lite' 
3. 'Leopard - Wordpress offload media.

If you are using a CDN to host external images, the featured image or images originally added to the listing disappears.

The issue is when you want to edit the submission. If you click 'save' all seems fine, when you go to the front end and refresh the featured image disappears. I have tried with with two different CDN plugins

To replicate,

Download any CDN external image plug that changes the URL of your images so they are sourced from the CDN URL. I used 'WP Offload Media Lite' and also used 'Leopard - Wordpress offload media.

Turn all unecessary plugins off only the plugins that work with wpjobmanager'

Ensure you are running the latest version of wordpress 5.5.1

Create a listing with a featured image and submit

Go to front end and check. Featured image is there and if you inspect the URL of the image, it points to the CDN URL.

Now go back and click edit the listing, and just save, you don't necessarily have to make any changes, but click save again.

Now go back to the listing. Featured image disappears.

WordPress Environment

WordPress Version: 5.5.1
WP Job Manager Version: 1.34.3
PHP Version: 7.2
Other important details: Used default wordpress theme and listable theme on codecanyon

**Comment by dave3322** [comment]
To add, I think this is not just an issue with images,
I think this is an issue with the logo / featured image 

I have done a lot of lame man testing ( not developer type with code)
- I turned everything off, only had wp job manager and cdn(s) on.
- on the same listing i created a gallery on thye backend.
- when you edit the listing and refresh, the gallery still shows and the gallery images are using the cdn url.
- I tried different themes, listify, listable, wordpress 2019, a few
- the issue persists. 
- contacted a few theme authors, they said the issue is with wp job manager and the logo/featured image area is not compatible with cdns on edit.

- the conclusion.
- I dont think this is wholly a cdn issue as gallerys images that point to cdns are ok
- the issue is the way the logo/featured image area uses images that point to a cdn

fyi - i have been looking at this issue for over 4 weeks. no resolution

**Comment by dave3322** [comment]
Anyone have an update?

**Comment by tripflex** [comment]
@dave3322 when you stated `Now go back and click edit the listing, and just save, you don't necessarily have to make any changes, but click save again.` are you talking about from the frontend or backend?  Or both?
